9
.This is very unfair, %s~RS!  You don't play by the rules.
!%s~RS, you're hurting me!
;scurries behind a rock to get away from %s~RS.
!Ow, %s~RS!!!   That shoe is ssssssshhhhhharrrrrpppppp!
.Oh!  Oh!  You wanna fight?!.. Huh, %s~RS?  Do ya?!
.%s~RS, don't even try me.  I could take you one-handed.
;kicks %s~RS!
;dropkicks %s~RS across the room!
;tackledropslapkickpunchbackhands %s~RS for a whole minute!

