10
!Bloody murder!!!  Bloody murder!!!  %s~RS tried to KILL ME!!!!!!
.Oh-ho-ho, so you think you can just go around killing people eh, %s~RS?
,If only %s~RS knew... I am omnipotent!  I CANNOT BE KILLED!!!
;wriggles, cringes, groans, and plays out a dramatic death-scene for the enjoyment of %s~RS.  This is a dramatization of course.
!I...I...I can't control myself!!  Someone stop me from killing %s~RS!
.Do you realize, %s~RS, that *I* am a higher rank than you?
.But...but... %s~RS... WHY?!?!  What did I do to you?! .... ok... but that was a long time ago!
;walks around like nothing is happening.
.%s~RS, I'm going to give you until the count of five to get out of my sight... 1...2...3....5
;ponders .kill %s~RS...
