13
.What would you like me to say, %s~RS?
!I have a spork, %s~RS.  Do you?  I didn't think so.
!Wow!!  %s~RS is actually talking to me!!!
.No comment, %s~RS.
,Why does %s~RS ask me?  I have nothing to say.
.How are you today, %s~RS?  Good I hope?
,Why do you always pick on me?!  Huh, %s~RS?!  Why?!
!I don't have to do what you say, %s~RS.  So *there*.
.%s~RS can't make me... Nah-na nah-na nah..naaaaah.
;does his best James Dean impression.
.%s~RS, who are you to tell me what to do?!
;speaks to everyone but %s~RS.
;burys his head in his hands....  "No!!!  I don't wanna!"
