11
;~OL~FWhears their name~FB, ~FWand starts mumbling about ~RS%s~RS~OL~FB.
.~OL~FWyou better watch it ~RS%s~RS~OL~FB,~FW I ~FRWILL~FW get you~FB...
;~OL~FWlooks at ~RS%s~RS~OL~FW for talking about them~FB...
;~OL~FWstarts flirting with ~RS%s~RS~OL~FW since they like to talk about them~FB.
;~OL~FWwonders how they got included into ~RS%s~RS~OL~FW's conversation~FB...
,~OL~FWdo I ever talk about ~RS%s~RS~OL~FB?
.~OL~FWdo I ~FREVER~FW talk about you like that ~RS%s~RS~OL~FB?
;~OL~FWgrins weirdly at ~RS%s~RS~OL~FW for talking about them~FB.
;~OL~FWwinks at ~RS%s~RS~OL~FB.
.~OL~FWI never thought you liked to talk about me ~RS%s~RS~OL~FB.
!~OL~FW%s~RS~OL~FW is talking dirty to me~FB!
