11
.~OL~FWLater ~RS%s~RS~OL~FB! ~OL~FWRemember to come back~FB!
!~OL~FWEveryone say goodbye to ~RS%s~RS~OL~FW because their leaving us~OL~FB.
,~RS%s~RS~OL~FW is leaving us so soon~FB?!?
.~OL~FWHasta luego~FB, ~RS%s~RS~OL~FB. ~OL~FWVeo tu manana~FB!
.~OL~FWYou can't leave us ~RS%s~RS~OL~FB! ~FWIt will be too boring then~FB!
;~OL~FWwalks ~RS%s~RS~OL~FW out to the door and snickers as they slap on a ~FB"~FWKick me~FB"~FW sign~FB.~FW
.~OL~FWFine ~RS%s~RS~OL~FB! ~OL~FWLeave us for something else~FB!
.~OL~FWI hope ~RS%s~RS~OL~FW comes back before I go crazy~FB...
.~OL~FWPeace out ~RS%s~RS~OL~FB, ~FWand don't get into too much trouble~FB!
.~OL~FWGoodbye ~RS%s~RS~OL~FB!
.~OL~FWShesh~FB, ~FWI just ~FRHAVE~FW to run everybody off the talker don't I ~RS%s~RS~OL~FB?
