10
.~OL~FWHello~RS %s~RS~OL~FB! ~OL~FWIts soo nice to see you~OL~FB!
.~OL~FWHeya %s~RS~OL~FB!  ~OL~FWHow are you today~OL~FB?
!~OL~FWLook everybody~FB!!~RS %s~RS~OL~FW's here~FB!
;~OL~FWgreets ~RS%s~RS~OL~FB.
,~OL~FWOh great~FB,~FW here comes %s~RS~OL~FB!
.~OL~FWGood day~FB,~RS %s~RS~OL~FB.~FW Thank's for coming back~FB.
.~OL~FWWelcome back~FB,~RS %s~RS~FB~OL!
;~OL~FWwas looking forward to your coming back ~RS%s~RS~OL~FB.
!~OL~FWWell~FB, ~FWWhadda ya know~FB? ~OL~FWIt's ~RS%s~OL~FB!
!~OL~FWWelcome to ~OL~FTE~RS~FTscape ~OL~FTT~RS~FTo ~OLT~RS~FThe ~OL~FTA~RS~FTrctic~RS %s~RS~OL~FB!
