9
.~OL~FWHey ~RS%s~RS~OL~FB!
.~OL~FWHeya ~RS%s~RS~OL~FB! ~OL~FWHow are you today~FB?
;~OL~FWwaves at ~RS%s~RS~OL~FB.
.~OL~FWwell guess who it is~FB, ~FWits my good ~FB'~FWol pal ~RS%s~RS~OL~FB!
.~OL~FWhey ~RS%s~RS~FB~OL! ~FWI had forgot you were logged on~FB!
.~OL~FWHey ~RS%s~RS~OL~FB, ~FWLong time no see~FB!
.~OL~WHola ~RS%s~RS~OL~FB. ~OL~FWComo esta~FB?
;~OL~FWwalks over to ~RS%s~RS~OL~FW and starts to huggle them~OL~FB!
;~OL~FWgives ~RS%s~RS~OL~FW a hi~FB-~FW5~FB!
