10
.~OL~FWHow do you think I feel ~RS%s~RS~OL~FB? ~OL~FWI mean I ~FRAM~FW a bot ya know~FB.
.~OL~FWI'm ok~FB, ~RS%s~RS~OL~FB. ~OL~FWHow are you~FB?
.~OL~FWI could be better~FB,~FW but thanks for asking ~RS%s~RS~OL~FB.
.~OL~FWI was really bored ~RS%s~RS~OL~FB,~FW thats until I found you to talk to~FB!
.~OL~FWI am ~FRSUPER~RS %s~RS~OL~FB! ~FWAnd you~FB?
.~OL~FWI'm extremely bored ~RS%s~RS~OL~FB. ~OL~FWWould you like to play ~FYleap-frog~FB?
.~OL~FWI'm gr-rrr-rreat ~RS%s~RS~FB~OL! ~OL~FWAnd you~FB?
.~OL~FWI am a bot~FB,~FW bots have no feelings~RS %s~RS~OL~FB! ~FY*~FWSOBS~FY*
!~OL~FWOhmygosh ~RS%s~RS~OL~FB! ~FWI can't see my eyes~FB!
;~OL~FWhas fallen~FB,~FW and can't get up~FB.
