11
;takes %s~RS's punches and delivers his own blows in return.
,Why do you do this to me, %s~RS?
!%s~RS is very violent.... yes... very violent indeed!
.Oh!  Oh!  You wanna fight?!.. Huh, %s~RS?  Do ya?!
.%s~RS, don't even try me.  I could take you one-handed.
!You wanna get hit?  %s~RS??
;slaps %s~RS!
;backhands %s~RS!
;punches %s~RS in the gut!
;punches %s~RS in the face!
!%s~RS... Don't *even* think about it, you wimp.
