16
.Just who do you think you're grinin' at, %s~RS?!
;winks at %s~RS.
.Wipe that smile off your face, %s~RS!
.Just happy to see me, eh %s~RS?
;smiles in %s~RS's general direction.
;flinches, then half-smiles at %s~RS.
;hands %s~RS a toothbrush.
!Gee, %s~RS, I didn't know you cared!
.Well, why didn't you just say so, %s~RS?!
,Playing 'hard-to-get' eh?  Two can play at that, %s~RS.
;smiles at %s~RS.
;poses and hopes %s~RS takes a picture.
;smiles... "Are you happy now, %s~RS?"
;has no teeth, %s~RS.
,All %s~RS ever wants... do this, do that.
;smiles happily at %s~RS... or is it a smirk?
