version       0.3
password      NU26GopoQybkU
promote_date  on Monday 10th September 2007 at 04:14am
times         1189375110 6308 6264 1189368801
levels        2 2 0 0
general       -1 0 0 0 1 0 0 1
user_set      0 0 0 23 1 1 1 0 0 0 1 0 #UNSET
user_ignores  0 0 0 0 0 0 0 0 0 1
fighting      0 0 0 0 6 10 1086 3000
purging       1 1279231110
last_site     darkfantastic.net  directors
mail_verify   #NONE
description   ~RS
in_phrase     enters
out_phrase    goes
email         #UNSET
homepage      #UNSET
recap_name    Addict
