version       0.3
password      NUUZ.4bv4lfBU
promote_date  on Saturday 22nd September 2007 at 04:16pm
times         1190450055 1084 517 1190448855
levels        15 15 0 0
general       -1 0 0 0 1 0 0 4
user_set      1 0 0 23 1 1 1 0 0 0 1 0 #UNSET
user_ignores  0 0 0 0 0 0 0 0 0 1
fighting      0 0 0 0 6 10 1013 3000
purging       1 1280306055
last_site     ppp34.stat126.pacific.net.ph  stlife
mail_verify   #NONE
description   The Man in the Iron Mask
in_phrase     enters
out_phrase    goes
email         #UNSET
homepage      #UNSET
recap_name    Aeon
