version       0.3
password      NUHo2D6Bdrx9E
promote_date  on Sunday 9th September 2007 at 09:08pm
times         1190446177 9630 37 1189342670
levels        12 12 0 0
general       -1 0 0 0 1 0 0 15
user_set      1 0 0 23 1 1 1 0 0 0 1 1 #UNSET
user_ignores  0 0 0 0 0 0 0 0 0 1
fighting      0 0 0 0 6 10 1122 3000
purging       1 1280302177
last_site     phenix.rootshell.be  stlife
mail_verify   #NONE
description   ~FR[ ~RSNight~RVRunners~RS~FR ]~RS
in_phrase     enters
out_phrase    goes
email         #UNSET
homepage      #UNSET
recap_name    Agentx
