version       0.3
password      NUNeRqwwRj3PA
promote_date  on Saturday 15th September 2007 at 07:13pm
times         1189854845 56 29 1189854788
levels        0 0 0 0
general       0 0 0 0 1 0 0 1
user_set      0 0 0 23 1 1 1 0 0 0 1 0 #UNSET
user_ignores  0 0 0 0 0 0 0 0 0 1
fighting      0 0 0 0 6 10 1000 3000
purging       1 1191582845
last_site     r31_acl1.gw.smartbro.net  directors
mail_verify   #NONE
description   ~OLa ~FRnewbie~FW.
in_phrase     enters
out_phrase    goes
email         #UNSET
homepage      #UNSET
recap_name    Allec
