version       0.3
password      NUnKH797jKPDc
promote_date  on Monday 10th September 2007 at 06:32am
times         1189377405 4460 4129 1189372800
levels        12 12 0 0
general       1 0 0 0 1 0 0 2
user_set      1 23 0 23 1 1 1 0 0 0 1 0 #UNSET
user_ignores  0 0 0 0 0 0 0 0 0 1
fighting      0 0 0 0 6 10 1060 3000
purging       1 1279233405
last_site     58.71.10.18  directors
mail_verify   #NONE
description   ~FB~BRd'POGI
in_phrase     enters
out_phrase    goes
email         #UNSET
homepage      #UNSET
recap_name    Avesicnarf
