version       0.3
password      NUzhJZrJi07IE
promote_date  on Thursday 13th September 2007 at 04:54pm
times         1190114025 2308 1017 1189673593
levels        2 2 0 0
general       -1 0 1 0 1 0 0 2
user_set      1 0 0 23 1 1 1 0 0 0 1 0 #UNSET
user_ignores  0 0 0 0 0 0 0 0 0 1
fighting      0 0 0 0 6 10 1031 3000
purging       1 1279970025
last_site     c-24-0-4-109.hsd1.nj.comcast.net  reception
mail_verify   #NONE
description   ~FG
in_phrase     enters
out_phrase    goes
email         #UNSET
homepage      #UNSET
recap_name    Backslash
