version       0.3
password      NURG/NYs8NKVE
promote_date  on Wednesday 12th September 2007 at 07:12am
times         1189595946 508 38 1189552288
levels        2 2 0 0
general       -1 0 1 0 1 0 0 3
user_set      1 0 0 23 1 0 1 0 0 0 1 0 #UNSET
user_ignores  0 0 0 0 0 0 0 0 0 1
fighting      0 0 0 0 6 10 1005 3000
purging       1 1279451946
last_site     bas2-unionville55-1242394294.dsl.bell.ca  reception
mail_verify   #NONE
description   Heart
in_phrase     enters
out_phrase    goes
email         #UNSET
homepage      #UNSET
recap_name    Brave
