version       0.3
password      BicolBot
promote_date  on Sunday 9th September 2007 at 08:40pm
times         1189695416 100028 9333 1189341034
levels        12 12 0 0
general       -1 0 0 0 1 0 0 6
user_set      2 -1 0 23 1 0 1 0 0 0 1 0 #UNSET
user_ignores  0 0 0 0 0 0 0 0 0 1
fighting      0 0 0 0 6 10 2386 3000
purging       1 1279551416
last_site     hackers.com  stlife
mail_verify   #NONE
description   ~OL~FYI'm~FRSo~FGPretty~FMRight~FWNow
in_phrase     walks in.
out_phrase    walks out
email         #UNSET
homepage      #UNSET
recap_name    ~OL~FGCel
