version       0.3
password      NUTcPvZjI29Zg
promote_date  on Saturday 15th September 2007 at 08:48pm
times         1189861920 1444 1429 1189860476
levels        0 0 0 0
general       4 0 0 0 1 0 0 1
user_set      0 0 0 23 1 1 1 0 0 0 1 0 #UNSET
user_ignores  0 0 0 0 0 0 0 0 0 1
fighting      0 0 0 0 6 10 1000 3000
purging       1 1191589920
last_site     dsl-nga-basic176.bti.net.ph.24.4.210.in-addr.arpa  directors
mail_verify   #NONE
description   sweet and lovable
in_phrase     enters
out_phrase    goes
email         #UNSET
homepage      #UNSET
recap_name    Celmari
