version       0.3
password      NUvjNwMViMkrI
promote_date  on Monday 10th September 2007 at 02:26pm
times         1189405725 138 114 1189405586
levels        0 0 0 0
general       0 0 0 0 1 0 0 1
user_set      0 0 0 23 1 1 1 0 0 0 1 0 #UNSET
user_ignores  0 0 0 0 0 0 0 0 0 1
fighting      0 0 0 0 6 10 1000 3000
purging       1 1191133725
last_site     75-161-20-131.albq.qwest.net  directors
mail_verify   #NONE
description   ~OLis a newbie~FW.
in_phrase     enters
out_phrase    goes
email         #UNSET
homepage      #UNSET
recap_name    Chet
