version       0.3
password      NUnfgG0HCRNF.
promote_date  on Monday 17th September 2007 at 07:35pm
times         1190029617 684 660 1190028931
levels        0 0 0 0
general       0 0 0 0 1 0 0 1
user_set      0 0 0 23 1 1 1 0 0 0 1 0 #UNSET
user_ignores  0 0 0 0 0 0 0 0 0 1
fighting      0 0 0 0 6 10 1000 3000
purging       1 1191757617
last_site     121.97.211.223.bti.net.ph  directors
mail_verify   #NONE
description   ~OLa ~FRnewbie~FW.
in_phrase     enters
out_phrase    goes
email         #UNSET
homepage      #UNSET
recap_name    Cuteako
