version       0.3
password      NUdawvJgYKXJs
promote_date  on Monday 10th September 2007 at 06:41am
times         1190429519 40192 7670 1189377636
levels        4 4 0 0
general       -1 0 0 0 1 0 0 8
user_set      1 25 0 23 1 1 1 0 0 0 1 0 #UNSET
user_ignores  0 0 0 0 0 0 0 0 0 1
fighting      0 0 0 0 6 10 1553 3000
purging       1 1280285519
last_site     c-71-58-64-229.hsd1.pa.comcast.net  stlife
mail_verify   #NONE
description   just is
in_phrase     enters
out_phrase    goes
email         derrecklowe@gmail.com
homepage      http://www.derrecklowe.name
recap_name    Derreck
