version       0.3
password      NUlQ1Qeoe4OgA
promote_date  on Monday 10th September 2007 at 04:56pm
times         1189420030 6092 6067 1189413932
levels        6 6 0 0
general       1 0 0 0 1 0 0 1
user_set      1 0 0 23 1 1 1 0 0 0 1 0 #UNSET
user_ignores  0 0 0 0 0 0 0 0 0 1
fighting      0 0 0 0 6 10 1076 3000
purging       1 1279276030
last_site     124.105.77.76.pldt.net  directors
mail_verify   #NONE
description   ako si blink
in_phrase     enters
out_phrase    goes
email         #UNSET
homepage      #UNSET
recap_name    Elmarino
