version       0.3
password      NUtzaVfoveuNY
promote_date  on Sunday 9th September 2007 at 07:46pm
times         1190516830 316312 65 1190030915
levels        15 15 0 0
general       -1 0 0 0 1 1 0 45
user_set      1 0 0 23 1 1 1 0 0 0 1 0 #UNSET
user_ignores  1 0 0 0 0 0 0 0 0 1
fighting      0 0 0 0 6 10 5367 3000
purging       1 1280372830
last_site     localhost  stlife
mail_verify   #NONE
description   ~FKHidden
in_phrase     enters
out_phrase    goes
email         #UNSET
homepage      #UNSET
recap_name    ~OL~FYJhong
