version       0.3
password      NUtzaVfoveuNY
promote_date  on Thursday 13th September 2007 at 03:56pm
times         1190180970 205408 163767 1189670111
levels        10 10 0 0
general       -1 0 0 0 1 0 0 5
user_set      2 0 0 23 1 0 1 0 0 0 1 0 #UNSET
user_ignores  0 0 0 0 0 0 0 0 0 1
fighting      0 0 0 0 6 10 3849 3000
purging       1 1280036970
last_site     hackers.com  reception
mail_verify   #NONE
description   ~OLCute~FR&~RS~OLSmart
in_phrase     enters
out_phrase    goes
email         jhocel@gmail.com
homepage      http://www.friendster.com/maricelniks
recap_name    ~FR~OLKate
