version       0.3
password      NUuBEzfNFDxks
promote_date  on Friday 28th November 2003 at 08:28am
times         1070179796 1604126 5537 1070174266
levels        14 14 0 0
general       -1 0 0 0 1 1 0 844
user_set      1 22 0 23 0 1 1 0 0 0 1 0 #UNSET
user_ignores  0 0 0 0 0 0 0 0 0 1
fighting      0 0 0 0 6 10 22878 3000
purging       0 1160035796
last_site     ppp252.pool1.mnl.skyinet.net  reception
mail_verify   amnuts351
description   (Jedi-Knight)
in_phrase     ~OL~FRe~RS~FRnter~OLs
out_phrase    ~OL~FRe~RS~FRxit~OLs
email         kelotz@supermail.com
homepage      www25.brinkster.com/kelotz
recap_name    Kelotz
