version       0.3
password      NU9G9WXi5byBs
promote_date  on Monday 10th September 2007 at 04:58pm
times         1189415169 498 481 1189414672
levels        0 0 0 0
general       0 0 0 0 1 0 0 1
user_set      0 0 0 23 1 1 1 0 0 0 1 0 #UNSET
user_ignores  0 0 0 0 0 0 0 0 0 1
fighting      0 0 0 0 6 10 1000 3000
purging       1 1191143169
last_site     210.4.38.67  directors
mail_verify   #NONE
description   ~OLis a newbie~FW.
in_phrase     enters
out_phrase    goes
email         #UNSET
homepage      #UNSET
recap_name    Kissame
