version       0.3
password      NU.Peb2Z8ur7Q
promote_date  on Saturday 15th September 2007 at 08:45pm
times         1189860671 372 355 1189860298
levels        0 0 0 0
general       4 0 0 0 1 0 0 1
user_set      0 0 0 23 1 1 1 0 0 0 1 0 #UNSET
user_ignores  0 0 0 0 0 0 0 0 0 1
fighting      0 0 0 0 6 10 1000 3000
purging       1 1191588671
last_site     d207-216-167-70.bchsia.telus.net  directors
mail_verify   #NONE
description   LoveTheme
in_phrase     enters
out_phrase    goes
email         #UNSET
homepage      #UNSET
recap_name    Lainecute
