version       0.3
password      NUa1m8qnMDA7.
promote_date  on Monday 10th September 2007 at 08:22am
times         1189383781 102 87 1189383679
levels        2 2 0 0
general       -1 0 0 0 1 0 0 1
user_set      2 0 0 23 1 1 1 0 0 0 1 0 #UNSET
user_ignores  0 0 0 0 0 0 0 0 0 1
fighting      0 0 0 0 6 10 1000 3000
purging       1 1279239781
last_site     58.69.4.116.pldt.net  directors
mail_verify   #NONE
description   o:
in_phrase     enters
out_phrase    goes
email         #UNSET
homepage      #UNSET
recap_name    Mai
