version       0.3
password      NUtzaVfoveuNY
promote_date  on Sunday 9th September 2007 at 08:38pm
times         1190116693 21342 89 1189341482
levels        3 3 0 0
general       -1 0 0 0 1 0 0 15
user_set      2 0 0 23 1 1 1 0 0 0 1 0 #UNSET
user_ignores  0 0 0 0 0 0 0 0 0 1
fighting      0 0 0 0 6 10 1291 3000
purging       1 1279972693
last_site     61.9.52.170.mozcom.net  reception
mail_verify   #NONE
description   ~OLCute~FR&~RS~OLSexy
in_phrase     enters
out_phrase    goes
email         #UNSET
homepage      #UNSET
recap_name    Maricel
