version       0.3
password      NUCZbG7Jgyh5c
promote_date  on Monday 10th September 2007 at 03:53pm
times         1189414676 3866 3858 1189410807
levels        0 0 0 0
general       12 0 0 0 1 0 0 1
user_set      0 0 0 23 1 1 1 0 0 0 1 0 #UNSET
user_ignores  0 0 0 0 0 0 0 0 0 1
fighting      0 0 0 0 6 10 1000 3000
purging       1 1191142676
last_site     124.6.185.100  directors
mail_verify   #NONE
description   shinigami
in_phrase     enters
out_phrase    goes
email         #UNSET
homepage      #UNSET
recap_name    Markian
