version       0.3
password      NUhbkgDHS.xYs
promote_date  on Saturday 15th September 2007 at 08:49pm
times         1189862628 2102 2085 1189860524
levels        2 2 0 0
general       -1 0 0 0 1 0 0 1
user_set      1 0 0 23 1 1 1 0 0 0 1 0 #UNSET
user_ignores  0 0 0 0 0 0 0 0 0 1
fighting      0 0 0 0 6 10 1028 3000
purging       1 1279718628
last_site     125.212.49.6  directors
mail_verify   #NONE
description   ~FK
in_phrase     enters
out_phrase    goes
email         #UNSET
homepage      #UNSET
recap_name    Messiah
