version       0.3
password      NUxxetGBcftFw
promote_date  on Saturday 15th September 2007 at 08:35am
times         1190465594 62040 693 1190464908
levels        12 12 0 0
general       -1 0 0 0 1 0 0 10
user_set      1 0 0 23 1 1 1 0 0 0 1 0 #UNSET
user_ignores  0 0 0 0 0 0 0 0 0 1
fighting      0 0 0 0 6 10 1856 3000
purging       1 1280321594
last_site     210.4.61.156  stlife
mail_verify   #NONE
description   is back
in_phrase     enters
out_phrase    goes
email         #UNSET
homepage      #UNSET
recap_name    Robodog
