version       0.3
password      NUsj10VNvpRzE
promote_date  on Saturday 15th September 2007 at 08:55pm
times         1189861007 92 72 1189860914
levels        0 0 0 0
general       0 0 0 0 1 0 0 1
user_set      0 0 0 23 1 1 1 0 0 0 1 0 #UNSET
user_ignores  0 0 0 0 0 0 0 0 0 1
fighting      0 0 0 0 6 10 1000 3000
purging       1 1191589007
last_site     124.106.223.121  directors
mail_verify   #NONE
description   ~OLa ~FRnewbie~FW.
in_phrase     enters
out_phrase    goes
email         #UNSET
homepage      #UNSET
recap_name    Smigul
