version       0.3
password      NURG/NYs8NKVE
promote_date  on Monday 10th September 2007 at 03:58pm
times         1189411259 212 177 1189411048
levels        2 2 0 0
general       -1 0 1 0 1 0 0 1
user_set      1 0 0 23 1 1 1 0 0 0 1 0 #UNSET
user_ignores  0 0 0 0 0 0 0 0 0 1
fighting      0 0 0 0 6 10 1002 3000
purging       1 1279267259
last_site     bas2-unionville55-1242395926.dsl.bell.ca  directors
mail_verify   #NONE
description   ~RS
in_phrase     enters
out_phrase    goes
email         #UNSET
homepage      #UNSET
recap_name    Tuna
