version       0.3
password      NUOt8xsBe.9dE
promote_date  on Thursday 13th September 2007 at 10:20pm
times         1190371432 40480 1634 1190103912
levels        12 12 0 0
general       -1 0 0 0 1 1 0 18
user_set      1 16 0 38 1 1 1 0 0 0 1 0 #UNSET
user_ignores  0 0 0 0 0 0 0 0 0 1
fighting      0 0 0 0 6 10 1548 3000
purging       1 1280227432
last_site     222.127.83.183  stlife
mail_verify   #NONE
description   ~FRVorsicht!
in_phrase     beams down
out_phrase    beams up
email         #UNSET
homepage      #UNSET
recap_name    ~FGUber
