version       0.3
password      NUD.C3ECDSfAA
promote_date  on Monday 17th September 2007 at 07:19pm
times         1190218869 228846 102030 1190116845
levels        15 15 0 0
general       -1 0 0 0 0 1 0 14
user_set      0 0 0 23 1 1 1 0 0 0 1 0 #UNSET
user_ignores  1 0 0 0 0 0 0 0 0 1
fighting      0 0 0 0 6 10 4169 3000
purging       1 1280074869
last_site     58.71.7.250  reception
mail_verify   #NONE
description   UTOT
in_phrase     enters
out_phrase    goes
email         #UNSET
homepage      #UNSET
recap_name    Valiant
