version       0.3
password      NUpy24g2q4Wdo
promote_date  on Monday 10th September 2007 at 06:32am
times         1189382103 6586 6577 1189375502
levels        3 3 0 0
general       1 0 0 0 1 0 0 1
user_set      2 0 0 23 1 1 1 0 0 0 1 0 #UNSET
user_ignores  0 0 0 0 0 0 0 0 0 1
fighting      0 0 0 0 6 10 1081 3000
purging       1 1279238103
last_site     121.1.53.7  directors
mail_verify   #NONE
description   ~OL~FGis so CUTE
in_phrase     enters
out_phrase    goes
email         #UNSET
homepage      #UNSET
recap_name    ~OL~FGYamster
