version       0.3
password      NU0DVIvsxzXmc
promote_date  on Sunday 9th September 2007 at 09:57pm
times         1189346412 192 179 1189346220
levels        0 0 0 0
general       0 0 0 0 1 0 0 1
user_set      0 0 0 23 1 1 1 0 0 0 1 0 #UNSET
user_ignores  0 0 0 0 0 0 0 0 0 1
fighting      0 0 0 0 6 10 1000 3000
purging       1 1191074412
last_site     121.97.175.223.bti.net.ph  directors
mail_verify   #NONE
description   ~OLis a newbie~FW.
in_phrase     enters
out_phrase    goes
email         #UNSET
homepage      #UNSET
recap_name    Zashi
