01/07 02:46: Made a request for an account.
01/07 02:47: Was auto-promoted to level GUEST.
01/07 02:47: ~OL~FGAutomatically promoted to next level: ~FWUSER
01/07 02:47: ~OLWas promoted  by Jhong to level ~FWTROPA.
14/09 15:48: ~OLWas promoted  by Jhong to level ~FWTROPA.
15/09 19:11: ~OLWas promoted  by Jhong to level ~FWTROPA.
15/09 19:11: ~OLWas promoted  by Jhong to level ~FWBOT.
15/09 19:11: ~OL~FGAutomatically promoted to next level: ~FWMANAGER
15/09 19:12: ~OL~FGAutomatically promoted to next level: ~FW*
21/09 18:21: ~OLWas promoted  by Jhong to level ~FWOPERATOR.
