27/06 00:52: Was initially created.
27/06 00:56: Made a request for an account.
27/06 00:56: Was auto-promoted to level GUEST.
27/06 00:56: ~OL~FGAutomatically promoted to next level: ~FWUSER
27/06 00:58: ~OLWas promoted  by Jhong to level ~FWCHATTER.
27/06 00:58: ~OLWas promoted  by Jhong to level ~FWSMOKERS.
27/06 00:58: ~OLWas promoted  by Jhong to level ~FWALCOHOLIC.
27/06 00:58: ~OLWas promoted  by Jhong to level ~FWFUCKER.
27/06 01:02: ~OLWas promoted  by Jhong to level ~FWADDICT.
27/06 01:02: ~OLWas promoted  by Jhong to level ~FWTROUBLEMAKER.
27/06 01:02: ~OLWas promoted  by Jhong to level ~FWPROGRAMMER.
27/06 01:02: ~OLWas promoted  by Jhong to level ~FWHACKER.
